### ISSUE TITLE
File gets split and @import statement gets added but IE8 doesn't render the imported file

### ISSUE THREAD

**Issue by jsheffers** [BlessCSS/gulp-bless#12]
I'm having trouble getting this to work, maybe I'm missing something.  Here is my gulp task.

```
gulp.task('css', function() {
  return gulp.src(paths.sass)
    .pipe($.plumber({errorHandler: onError}))
    .pipe($.sass({
        outputStyle: 'compressed',
        errLogToConsole: false,
        sourceComments: true,
        // compressed, expanded
    }))
    .pipe($.autoprefixer())
    .pipe(gulp.dest('../stylesheets'))
    .pipe($.bless())
    .pipe(gulp.dest('../stylesheets'))
    .pipe($.notify("Updated CSS"));
});
```
This seems to generate the file correctly.  I get a CSS file with an @import statement at the top that is importing a blessed1.css file.  Everything seems to work ok except not all of the styles get rendered.

If I remove bless and manually split the files and reference them with the link tag it works as expected.  However, if I link just the first one and I @import the other it doesn't work.  Am I missing something here?  This may not be a problem with this plugin, but it does say it works with < IE10 and I can't get it to function properly.

Thanks for any help.

**Comment by jsheffers** [comment]
As a follow up, the styles I'm missing are there if I visit the stylesheet directly in the browser, they just aren't there when I use the IE dev tools.

**Comment by adam-lynch** [comment]
@jsheffers ah I'm sorry I took so long getting back to you. I read the notification and mean to come back to it but forgot. 

I'm not really sure. I don't use `@import` for a few reasons. Is the URL in the `@import` correct? This is pretty hard for me to troubleshoot :/ Wish I could see it.

I could be related to something else though too. 

- Could it be that you're using HTML5 elements? 
- In the `@import`ed stylesheet, could you add some CSS for testing? On a simple element, like `body { background: red; }` for example.
- Is your main `link` simple? Like `<link rel="stylesheet" href="style.css">`.
- Maybe I'm missing something obvious but why do you have `gulp.dest('../stylesheets')` twice in your pipeline?

**Comment by josephnvn** [comment]
Try this :  imports: false
.pipe($.bless({
                        compress : true,
                        imports: false,
                        log: true
                    }))

**Comment by adam-lynch** [comment]
Sure this is a problem with gulp-bless and not bless? 

Side note: I really need to update this module to Bless 4

**Comment by adam-lynch** [comment]
>Side note: I really need to update this module to Bless 4

Nevermind, 4.0.0 isn't out yet

**Comment by ArtbyArjan** [comment]
@adam-lynch In your https://github.com/BlessCSS/gulp-bless/issues/12#issuecomment-93056331 you say
> Could it be that you're using HTML5 elements?

Are you implying you can't use HTML5 in your css? Like `header` or `section`?

**Comment by adam-lynch** [comment]
@ArtbyArjan No not exactly. Just that without [html5shiv](https://github.com/afarkas/html5shiv), there might be some issues.

**Comment by adam-lynch** [comment]
Going to close this as bless was rewritten.
