### ISSUE TITLE
When using gulp-bless in conjunction with gulp-sourcemaps the sourcemaps are invalid

### ISSUE THREAD

**Issue by Track0** [BlessCSS/gulp-bless#14]
When running sourcemaps with bless, the sourcemaps generated are not valid, or not present. If I run the sourcemaps prior to bless it generates invalid sourcemaps. If I run bless before sourcemaps, no sourcemap is generated.

      return gulp.src(sourceFiles)
        .pipe(plumber())
        .pipe(tokenReplace(tokenOptions))
        .pipe(sourcemaps.init())
        .pipe(sass({includePaths: includePaths}))
        .pipe(autoprefixer('last 1 version', '> 1%', 'ie 8'))
        .pipe(minify())
        .pipe(sourcemaps.write('./'))
        .pipe(bless({imports: false}))
        .pipe(gulp.dest(destinationFolder));
    };

**Comment by adam-lynch** [comment]
Ok, thanks. I guess bless needs to support sourcemap generation itself first though.

**Comment by adam-lynch** [comment]
https://github.com/paulyoung/bless.js/issues/33#issuecomment-96856387

**Comment by mapeter90** [comment]
Is there no workaround? 
In the readme of gulp-bless it says external sourcemaps can be used. 
https://github.com/adam-lynch/gulp-bless#a-note-about-sourcemaps

**Comment by adam-lynch** [comment]
Ah I forgot that was added in #4. By "external" I assume you mean not inline... the bit in the readme only concerns inline sourcemaps and it's recommending not to pass those even. @Harrisonbro want to chime in?

**Comment by kevin-smets** [comment]
Any news on this? When running with gulp-bless, sourcemaps does not work at all for me. Neither external nor internal.. As soon as I remove gulp-bless from the pipeline, it's fixed :/.

**Comment by adam-lynch** [comment]
> /edit: should've checked the bless issue first, seems they're still tackling it.

@kevin-smets yeah but just in case it helps: you're probably looking for sourcemaps for debugging? I.e. in nice developer tools like Google Chrome's. You shouldn't use the "blessed" CSS files for Chrome, etc. anyway. What I'd suggest is outputting the CSS file as is, also outputting the "blessed" files, and only loading the "blessed" files for IE10- (using conditional comments).
