### ISSUE TITLE
Split based on file size for IE <= 9

### ISSUE THREAD

**Issue by shannonhochkins** [BlessCSS/gulp-bless#19]
I've also noticed that IE <=9 has a file SIZE limit of 288kb, rules are only read upto the point of the 288kb mark, IE does not read anything past this limit. I've hit this issue multiple times without actually hitting the limitations already taken care of with Bless. To make it even more awesomer it would be great if we could also factor in the file size and split accordingly.

Src: http://joshua.perina.com/africa/gambia/fajara/post/internet-explorer-css-file-size-limit

**Comment by mtscout6** [comment]
Related to BlessCSS/bless#41.

In general the stance has been that this isn't BlessCSS's responsibility. Have you tried running your CSS through a minifier? That would coupled with BlessCSS would likely bring your file size below the limit.

**Comment by adam-lynch** [comment]
Yep.

**Comment by shannonhochkins** [comment]
@mtscout6 & @adam-lynch  "Bless provides an elegant solution to a lesser-known bug in Internet Explorer which causes CSS to be completely ignored.", straight from the website!

Any css after 288kb is completely ignored, might I say that this is exactly an issue relating to IE and I really do believe that this is something the Bless should take care of as it's 100% related to the tagline description on blesscss.com
