### ISSUE TITLE
gulp-bless 3.1.0 stopped dividing files into parts

### ISSUE THREAD

**Issue by mgol** [BlessCSS/gulp-bless#27]
My Gulp css task is as follows:
```js
const gulp = require('gulp');
const less = require('gulp-less');
const cleanCSS = require('gulp-clean-css');
const bless = require('gulp-bless');

gulp.task('css', () =>
    gulp.src([/* some paths */]
        .pipe(less())
        .pipe(cleanCSS())
        .pipe(bless({
            force: true,
            imports: false,
        }))
        .pipe(gulp.dest(/* dest dir */))
);
```

After upgrading `gulp-less` from `3.0.1` to `3.1.0`, the `bless` pipe:

1. Is no longer keeping the CSS files minified, it beautifies them.
2. The final files are not blessed, they're all in single undivided files.

**Comment by mgol** [comment]
I understand that the logic behind Bless 4.x has changed and it now requires minification after being run but it's a breaking change nonetheless.

**Comment by mgol** [comment]
Moving the `cleanCSS` line after the `bless` one makes it split files again. Weird.

**Comment by adam-lynch** [comment]
I *think* this is fixed. See https://github.com/BlessCSS/gulp-bless/issues/22#issuecomment-205973763. Correct me if I'm wrong.
