### ISSUE TITLE
What is the correct method to incorporate sourcemaps?

### ISSUE THREAD

**Issue by mderoche** [BlessCSS/gulp-bless#28]
On the readme, gulp-bless indicates only that "_this can be used with gulp-sourcemaps_", but it doesn't provide any details on that usage.

I am attempting to use it in the following manner, but this ends up freezing the process:

```
gulp.src('/path/to/app.scss'))
    .pipe(sourcemaps.init())
    .pipe(sass({
        style: 'expanded'
    }))
    .pipe(autoprefixer())
    .pipe(sourcemaps.write())
    .pipe(bless({
        imports: false
    }))
    .pipe(gulp.dest('/path/to/compiled-css'));
```

If I put the bless before the sourcemaps write, then the sourcemaps never make it to the blessed CSS files.

Is this the recommended pattern and something else in my code is causing this issue?  If not, what is the intended method?

Thanks for any input.

Full SO question here:  http://stackoverflow.com/questions/38250245/sourcemaps-with-gulp-bless

**Comment by entozoon** [comment]
+1

**Comment by entozoon** [comment]
My current workaround is to have two separate gulp modes - development and product that run like this:
Development: Adds sourcemaps (no minification or bless)
Production: Bless and minification (no sourcemaps)

(this can all be done in the same gulp file using gulp-util if statements within the various .pipe() )

**Comment by adam-lynch** [comment]
@mderoche you need to put `.pipe(sourcemaps.write())` at the end before you `gulp.dest`. See https://www.npmjs.com/package/gulp-sourcemaps#usage. Let me know if this doesn't work and I'll investigate with you.

@entozoon yeah that's good but only a separate topic. @mderoche is having trouble writing sourcemaps at all (not dev vs. prod).

**Comment by sb-lc** [comment]
what should the sourcemap files look like, I already have main.css.map, should I expect to see one called main-blessed1.css.map to main my main-blessed1.css file? If thats how it works then this is not working for me. main.css has this at the end of the file:

/*# sourceMappingURL=main.css.map */

main-blessed1.css does NOT have /*# sourceMappingURL=main-blessed1.css.map */

**Comment by adam-lynch** [comment]
@sb-lc you should have a single sourcemap file which contains references for each manipulation to the file.

**Comment by sb-lc** [comment]
thanks, there is no reference to my dist css files in the map file, i thought the link was in the css, like /*# sourceMappingURL=main.css.map */. that is what I have but no equivalent linkage to the blessed css file

**Comment by sb-lc** [comment]
on further inspection, there is actuall a reference in the map file but just to main.css

"file":"main.css"

no mention of the blessed css file

**Comment by sb-lc** [comment]
ah isee, the link is in the main.css file @import url('main-blessed1.css?z=20');

**Comment by sb-lc** [comment]
so am i right in thinking that there should be only one map file (main.css.map) ?

**Comment by adam-lynch** [comment]
>so am i right in thinking that there should be only one map file (main.css.map) ?

Yep
