### ISSUE TITLE
Is README.md up-to-date?

### ISSUE THREAD

**Issue by SergTanchenko** [BlessCSS/gulp-bless#43]
Piece of text from README.md:
> bless(options).
> imports - A boolean (which defaults to true). Determines whether or not the first chunk / "blessed" file @imports the others.

**Is it truth?**

I'm using gulp-bless 3.2.1
I have a big css file **styles.min.css**. After bless is applied I got:
- **styles.min-blessed1.css**
- **styles.min.css**

**styles.min.css** contains this `@import url("styles.min-blessed1.css?z=25");`

It is not correct behavior according to documentation, isn't it?

**Comment by alvinlin123** [comment]
@SergTanchenko ``sytle.min.css`` is actually consider as "first chcunk" so I think the documentation is correct; we probably can change the wording a bit if you find it confusing, or we can add examples?

**Comment by SergTanchenko** [comment]
great idea about examples, I think it will be helpful
